# This query is used as an example and for testing the query parser.
# It should not be used in production.

# URI will be injected to prefixes with ?... variable at runtime
# Don't specify explicit URI here to void unnecesary coupling
PREFIX geo: ?geo
PREFIX wikibase: ?wikibase
PREFIX wdt: ?wdt
PREFIX bd: ?bd
SELECT ?place ?placeLabel ?location WHERE {
    # By convention variable with ?_... syntax will be injected at runime
    values ?midPoint {?_pointValue}
    # Use the around service
    SERVICE wikibase:around {
        ?place wdt:P625 ?location .
        bd:serviceParam wikibase:center ?midPoint .
        # By convention variable with ?_... syntax will be injected at runime
        bd:serviceParam wikibase:radius ?_radius .
    }
    # Use the label service to get the English label
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language ?_language .
    }
}