PREFIX geo: ?geo
PREFIX wikibase: ?wikibase
PREFIX wdt: ?wdt
PREFIX bd: ?bd
SELECT ?place ?placeLabel ?location WHERE {
    values ?midPoint {?pointValue^^geo:wktLiteral}
    # Use the around service
    SERVICE wikibase:around {
        ?place wdt:P625 ?location .  # Looking for items with coordinate locations(P625)
        bd:serviceParam wikibase:center ?midPoint .
        bd:serviceParam wikibase:radius ?radius .
    }
    # Use the label service to get the English label
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en" .
    }
}