PREFIX geo: ?geo
PREFIX wikibase: ?wikibase
PREFIX wdt: ?wdt
PREFIX bd: ?bd
SELECT * WHERE {
    values ?_center {?center}
    VALUES ?_radius {?radius}
    # Use the around service
    SERVICE wikibase:around {
        ?place wdt:P625 ?location .  # Looking for items with coordinate locations(P625)
        bd:serviceParam wikibase:center ?_center .
        bd:serviceParam wikibase:radius ?_radius .
    }
    # Use the label service to get the English label
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en" .
    }
}