server:
  port: 8086

keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: Explorer
  resource: explorer-user-app
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true
  public-client: true
  principal-attribute: preferred_username

explorer:
  gis:
    wikidata-sparql-url: https://query.wikidata.org/sparql
    prefix-uri-file: classpath:sparql.properties
    query-dir: classpath:sparql/**/*.sparql