PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?place ?placeLabel ?location ?instanceOfLabel WHERE {
	VALUES ?midPoint {"Point(-2.096472,57.1443733)"^^geo:wktLiteral}

	{ # Use the around service
		SERVICE wikibase:around {
			?place wdt:P625 ?location .  # Looking for items with coordinate locations(P625)
			bd:serviceParam wikibase:center ?midPoint .
			bd:serviceParam wikibase:radius "0.5" .
		}
	}

	{
		VALUES ?included { wd:Q12280 wd:Q811979 wd:Q3947 }
		VALUES ?excluded { wd:Q3947 }
		?place p:P31/ps:P31/wdt:P279* ?included .
		FILTER NOT EXISTS { ?place p:P31/ps:P31/wdt:P279* ?excluded. }
	}

	{
		?place wdt:P31 ?instanceOf .
		?instanceOf rdfs:label ?instanceOfLabel FILTER (LANG(?instanceOfLabel) = "en") .

		?place rdfs:label ?placeLabel FILTER (LANG(?placeLabel) = "en") .
	}

} LIMIT 100