# From provided entities, return those which belong to included categories and discard those which belong to excluded categories

SELECT ?subject WHERE {


    VALUES ?subject  { ?@subject }  # List of entities for evaluation. e.g. wd:Q387736 wd:Q866761 wd:Q892022
    VALUES ?included { ?@include }  # List of categories to include e.g. wd:Q12280 wd:Q811979 wd:Q3947
    VALUES ?excluded { ?@exclude }  # List of categories to exclude e.g. wd:Q12280 wd:Q811979 wd:Q3947

    # Select subjects which have a categoriy that is 1,2,3,4 steps removed from parent category.
    # This is much more efficient that using a wildcard path operator e.g. ?subject p:P31/ps:P31/wdt:P279* ?included.
    # However, any entity that is > 4 steps from it's parent category will be ignored.
    ?subject
        p:P31/ps:P31/wdt:P279
        | p:P31/ps:P31/wdt:P279/wdt:P279
        | p:P31/ps:P31/wdt:P279/wdt:P279/wdt:P279
        | p:P31/ps:P31/wdt:P279/wdt:P279/wdt:P279/wdt:P279 ?included .


    #OPTIONAL {?subject p:P31/ps:P31/wdt:P279 ?included .}
    #FILTER NOT EXISTS { ?subject p:P31/ps:P31/wdt:P279* ?excluded. }

    #?subject wdt:P31 ?category .
    #?category rdfs:label ?categoryLabel FILTER (LANG(?categoryLabel) = "en") .

} LIMIT 100