keycloak:
  auth-server-url: http://10.1.0.20:8083/auth
  realm: Explorer
  resource: explorer-user-app
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true
  public-client: true
  principal-attribute: preferred_username
spring:
  session:
    store-type: none
    timeout: 600